#!/usr/bin/env ruby

# change this to something else, if deploying as a gem, or whatever.
siorack_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
$:.unshift(File.join(siorack_dir, 'lib'))

require 'rubygems'

gem 'thin'
require 'thin'

gem 'redis'
require 'redis'

gem 'json'
require 'json'

require 'palmade/socket_io_rack'
Thin.send(:include, Palmade::SocketIoRack::Mixins::Thin)

class Chat < Palmade::SocketIoRack::Base
  def initialize(options = {})
    super(options)
    @buffer = []
  end

  def on_connect(sid)
    EM.add_timer(1) do
      reply(sid, {:buffer => @buffer}.to_json)
      broadcast({:announcement => "#{sid} has joined the chat room"}.to_json)
    end
  end

  def on_message(sid, msg)
    message = {:message => [sid, msg]}
    @buffer << message
    @buffer.shift if @buffer.count > 15
    send_to = @sessions.keys
    send_to.delete sid
    multicast send_to, message.to_json
  end

  def on_disconnected(sid)
    broadcast({:announcement => "#{sid} has left the chat room (disconnected)"}.to_json)
  end
end

Thin::Server.start('127.0.0.1', 3000) do
  use Rack::CommonLogger

  map '/' do
    use(Palmade::SocketIoRack::Middleware,
        :resources =>  {
          '/chat' => 'Chat'
        })

    run Rack::File.new(File.join(siorack_dir, 'examples'))
  end
end
