#!/usr/bin/env ruby

# change this to something else, if deploying as a gem, or whatever.
siorack_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
$:.unshift(File.join(siorack_dir, 'lib'))

require 'rubygems'

gem 'thin'
require 'thin'

gem 'redis'
require 'redis'

gem 'json'
require 'json'

require 'palmade/socket_io_rack'
Thin.send(:include, Palmade::SocketIoRack::Mixins::Thin)

class Chat < Palmade::SocketIoRack::Base
  def on_connect
    reply({:buffer => [{:announcement => 'Welcome to the chat room'}]}.to_json)
  end

  def on_message(msg)
    reply({:message => ['sessionid', msg]}.to_json)
  end
end

Thin::Server.start('127.0.0.1', 3000) do
  use Rack::CommonLogger

  map '/' do
    use(Palmade::SocketIoRack::Middleware,
        :resources =>  {
          '/chat' => 'Chat'
        })

    run Rack::File.new(File.join(siorack_dir, 'examples'))
  end
end
